spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visitor_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  jwtSecret: i6QWxbho2ov9CPZCq1PgrxVoR3F0cOtAkxOfLIwTCSkZ4P2YvVHVLCyAx7D6DyN7o/JvXMvSRng1IppwObFyzA==
  jwtExpirationMs: 86400000
google:
  vision:
    apiKey: AIzaSyDgcjwyz6MZ04vJMAxN1WAEdW8VJng1MD4
docai:
  endpoint: "https://us-documentai.googleapis.com"
  processor-name: "projects/442256500910/locations/us/processors/a6070b6f8153e1b6"

gcp:
  credentials:
    file: "/Users/sasanktalluri/Documents/visitortrackingocr-056f86afc3e1.json"  # <-- put your saved path here
